
options:
  max-time: 10

pipelines:
  default:
    - parallel:
      - step:
          name: Build & Test 3.7
          image: python:3.7
          caches: &caches
            - pip
          script: &build_test
            - apt-get update
            - apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev git
            - mkdir -p /etc/assemblyline/
            - mkdir -p /var/cache/assemblyline/
            - mkdir -p /var/lib/assemblyline/
            - cp test/bitbucket/config.yml /etc/assemblyline
            # Install al common from source
            - git clone git@bitbucket.org:cse-assemblyline/alv4.git ~/alv4
            - cd ~/alv4 && pwd
            # Try to checkout the matching branch, if the command fails, don't care.
            - git checkout -b $BITBUCKET_BRANCH -t origin/$BITBUCKET_BRANCH || true
            - pip install --no-cache-dir -e .
            # Install and test al service server
            - cd $BITBUCKET_CLONE_DIR && pwd
            - pip install --no-cache-dir -r test/requirements.txt
            - pip install --no-cache-dir -e .
            - python -m assemblyline_service_server.app &
            - pytest -rsx -vv
          services: &services
            - elasticsearch
            - redis
            - minio
      - step:
          name: Build & Test 3.8
          image: python:3.8
          caches: *caches
          script: *build_test
          services: *services
  tags:
    v*:
      - step:
          name: Build Package
          image: python:3.8
          script:
            - pip install --no-cache-dir wheel
            - python setup.py bdist_wheel
            - ls dist/
          artifacts:
            - dist/*
      - parallel:
        - step:
            name: Test 3.7
            image: python:3.7
            script: &deploy_test
              - rm -rf service setup.py  # Make sure we are running on the package from the prior build
              - apt-get update
              - apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev
              - pip install --no-cache-dir -f dist assemblyline-service-server
              - mkdir -p /etc/assemblyline/
              - mkdir -p /var/cache/assemblyline/
              - cp test/bitbucket/config.yml /etc/assemblyline
              - pip install --no-cache-dir -r test/requirements.txt
              - python -m assemblyline_service_server.app &
              - pytest -rsx -vv
            services: *services
        - step:
            name: Test 3.8
            image: python:3.8
            script: *deploy_test
            caches: *caches
            services: *services
      - step:
          name: Deploy to Test PyPI
          image: python:3.8
          deployment: test_pypi
          script:
            - pip install --no-cache-dir twine
            - ls dist
            - twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
      - step:
          name: Deploy to PyPI
          image: python:3.8
          deployment: pypi
          script:
            - pip install --no-cache-dir twine
            - ls dist
            - twine upload --skip-existing dist/*
      - step:
          name: Deploy to Docker Hub
          image: python:3.8
          services: [docker]
          deployment: container
          script:
            - export TAG=${BITBUCKET_TAG#v}
            - until pip install --no-cache-dir assemblyline-service-server== 2>&1 | grep -q $TAG; do sleep 2; done
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build --build-arg version=$TAG -t cccs/assemblyline-service-server:$TAG -t cccs/assemblyline-service-server:latest docker
            - docker push cccs/assemblyline-service-server
definitions:
  services:
    elasticsearch:
      image: sgaroncse/elasticsearch:7.6.0
      memory: 768
      environment:
        ES_JAVA_OPTS: '-Xms256m -Xmx256m'
        DISCOVERY_TYPE: 'single-node'

    redis:
      image: redis
      memory: 256

    minio:
      image: sgaroncse/minio
      memory: 256
      environment:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
